# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import animation_ml_pb2 as animation__ml__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in animation_ml_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TextToMotionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateMotion = channel.unary_unary(
                '/animation_ml.TextToMotionService/GenerateMotion',
                request_serializer=animation__ml__pb2.MotionRequest.SerializeToString,
                response_deserializer=animation__ml__pb2.MotionResponse.FromString,
                _registered_method=True)
        self.GetServerStatus = channel.unary_unary(
                '/animation_ml.TextToMotionService/GetServerStatus',
                request_serializer=animation__ml__pb2.StatusRequest.SerializeToString,
                response_deserializer=animation__ml__pb2.StatusResponse.FromString,
                _registered_method=True)


class TextToMotionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateMotion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServerStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TextToMotionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateMotion': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateMotion,
                    request_deserializer=animation__ml__pb2.MotionRequest.FromString,
                    response_serializer=animation__ml__pb2.MotionResponse.SerializeToString,
            ),
            'GetServerStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerStatus,
                    request_deserializer=animation__ml__pb2.StatusRequest.FromString,
                    response_serializer=animation__ml__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'animation_ml.TextToMotionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('animation_ml.TextToMotionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TextToMotionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateMotion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/animation_ml.TextToMotionService/GenerateMotion',
            animation__ml__pb2.MotionRequest.SerializeToString,
            animation__ml__pb2.MotionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServerStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/animation_ml.TextToMotionService/GetServerStatus',
            animation__ml__pb2.StatusRequest.SerializeToString,
            animation__ml__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
